In [1]:
import os
from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

from langchain.agents import load_tools
from langchain.agents import initialize_agent

import csv
from langchain.chains.conversation.memory import ConversationBufferMemory
from langchain.chains import ConversationChain

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import cohen_kappa_score
import pandas as pd
import numpy as np
import re
from ast import literal_eval

In [2]:
os.environ['OPENAI_API_KEY'] = "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"
#os.environ['SERPAPI_API_KEY'] = '5ef522f358c7b54b6b86caf25bb85cdcace48af848db79ec66c1eb8998bf0a90'

In [3]:
data = np.load(r"C:\Users\fredp\Desktop\MS_Lab\LLM\Optimize with LLM\data\clf_data.npy")
X = np.copy(data[:,:-1])
y = np.copy(data[:,-1])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [4]:
def get_test_score(H1, H2, H3, H4):
    model = RandomForestClassifier(n_estimators=H1, min_samples_split=H2, max_depth=H3, min_samples_leaf=H4, random_state=42)
    model.fit(X_train, y_train)

    y_pred_test = model.predict(X_test)
    test_score = cohen_kappa_score(y_test, y_pred_test)
 
    return test_score

In [9]:
def get_record_H1H2(tabu_list, solution, outbound, lower_H1=20, upper_H1=200, lower_H2=20, upper_H2=200, lower_H3=20, upper_H3=200, lower_H4=20, upper_H4=200):
    memory = ConversationBufferMemory()
    llm = OpenAI(temperature=0.0)
    gpt = ConversationChain(
        llm=llm,
        verbose=False,
        memory=ConversationBufferMemory()
    )
    w = gpt.predict(input="A simple way to setup a search algorithm consists in defining a vector of lower bounds \
                a = (a1, a2, …, am) and a vector of upper bounds b = (b1, b2, …, bm) for each component of \
                νector, which is our solution space. Tabu Search works by maintaining a list of recently visited solutions, called a tabu list, to avoid revisiting them immediately.\
                Tabu Search explores the solution space by evaluating neighboring solutions and selecting the best one that is not on the tabu list.\
                The tabu size determines how many moves are remembered as forbidden. \
                We find neighbors by adding or subtracting 2 to different element of the original solution and store the moving operator index in tabu list. \
                Given a solution (a,b,c) and tabu list [1, -2] with size 2, the neighbors of solution will be [a+2, b, c, d] \
                , [a,b+2,c,d], [a,b,c+2,d], [a,b,c,d+2], [a-2,b,c,d], [a,b-2,c,d], [a,b,c-2,d], [a,b,c,d-2] whose operator indexes are\
                1, 2, 3, 4, -1, -2, -3, -4 respectively because we acquire them by adding 2 or minus 2 to the corresponding element.\
                For example, operator index of [a-2,b,c,d] is -1 because we minus 2 to the first element of list. The minus sign denotes\
                minus and 1 denotes first element of list. Similarly, operator index of [a,b+2,c,d] is 2 because we plus 2 to \
                the second element of list and operator index of [a,b-2,c,d] is -2 because we minus 2 to the second element of list. \
                However, [a+2, b, c, d] and [a-2,b,c,d] is invalid because we acquire [a+2, b, c, d] by adding 2 to\
                the first element and [a-2,b,c,d] from subtracting 2 from the second element, which violates the tabu 1 and -2 in the tabu list.\
                This means that valid solutions are the ones whose moving operator index are not in tabu list, which are \
                [a,b+2,c,d], [a,b,c+2,d], [a,b,c,d+2], [a,b-2,c,d], [a,b,c-2,d], [a,b,c,d-2].")
    print(w)

    k = gpt.predict(input="you are a parameter optimizer using Tabu search. I will give you several parameter names and the range of each\
                        parameter, I will give you all the parameters I have tested and the test score of each set\
                        of parameters in the format of ({H1}, {H2}, {H3}, {H4}). for \
                        example, (10, 10, 10, 10) and tabu list = [1,-1,2,-2] please give me the valid neighbors of the given solution\
                        whose corresponding moving operator index is not in tabu list, which will be (10,10,12,10)\
                    , (10,10,10,12), (10,10,8,10), (10,10,10,8) in this case.")
    print(k)
    t = gpt.predict(input="Given solution (20, 20, 20, 20) and tabu list = [1,-1,3,-3] please give me the valid neighbors of the given solution\
                        whose corresponding moving operator index is not in tabu list.")
    print(t)

    r = gpt.predict(input=f"given hyperparameter H = [H1, H2, H3, H4] where H1 in [{lower_H1}, {upper_H1}], H2 in [{lower_H2}, {upper_H2}], \
                H3 in [{lower_H3}, {upper_H3}], H4 in [{lower_H4}, {upper_H4}]. What is the search space?")
    #print(r)
    response = gpt.predict(input=f"given hyperparameter H = [H1, H2, H3, H4] where H1 in [{lower_H1}, {upper_H1}], H2 in [{lower_H2}, {upper_H2}], \
                H3 in [{lower_H3}, {upper_H3}], H4 in [{lower_H4}, {upper_H4}]. The tabu list is:\
                {tabu_list}, and the current solution is {solution} please give me all valid solutions among neighbors and its corresponding moving index\
                in form be like [a,b,c,d,i]. Don't output any words beside the list! For example, output:[[a,b,c,d,i], [e,f,g,h,m]]")

    while (response[0]!="["):
        response = response.lstrip(response[0])
    while (response[-1]!="]"):
        response = response.rstrip(response[-1])
    print(response)
    res = literal_eval(response)

    neighbors = np.array(res)
    print(neighbors)
    print(neighbors.shape)
    neighbor_scores = [] 
    for i in range(neighbors.shape[0]):
        score = get_test_score(neighbors[i][0], neighbors[i][1], neighbors[i][2], neighbors[i][3])
        neighbor_scores.append([score, i])
    score_rank = sorted(neighbor_scores, reverse = True)
    bestrow = score_rank[0][1]
    H1, H2, H3, H4 = np.copy(neighbors[bestrow][:-1])
    tabu_list.append(neighbors[bestrow][-1])


    if H1 > upper_H1 or H1 < lower_H1 or H2 > upper_H2 or H2 < lower_H2 or H3 > upper_H3 or H3 < lower_H3 or H4 > upper_H4 or H4 < lower_H4: 
        message = f'(H1, H2) = ({H1}, {H2}, {H3}, {H4}) is out of bound, better solution may exists outside the search space'
        print(message)
        outbound = True

    return H1, H2, H3, H4


#record_message = ""
#record_list = []
tabu_list = []
scores = []
solution = (20,50,70,100)
size = 2
iteration = 1000
iter = 0
outbound = False
while iter <= iteration:
    H1, H2, H3, H4 = get_record_H1H2(tabu_list, solution, outbound)
    if outbound == True:
        print("current best solution:", solution, "score:", scores[-1])
        break
    solution = (H1, H2, H3, H4)
    print(solution)
    test_score = get_test_score(H1, H2, H3, H4)

    print(f'test_score of ({H1}, {H2}, {H3}, {H4}) is {test_score}')
    #record_message += f"({H1}, {H2}, {H3}, {H4}) = {test_score:.3f}\n"
    #record_list.append((H1, H2, H3, H4))
    scores.append(test_score)

    if len(tabu_list) > size:
        tabu_list.pop(0)
    print(tabu_list)
    iter += 1
if outbound == False:
    print("Search Ends!!")
    print("best solution:", solution, "score:", scores[-1])



 I understand. So, to summarize, Tabu Search works by maintaining a list of recently visited solutions, called a tabu list, to avoid revisiting them immediately. The tabu size determines how many moves are remembered as forbidden. Valid solutions are the ones whose moving operator index are not in the tabu list, which are [a,b+2,c,d], [a,b,c+2,d], [a,b,c,d+2], [a,b-2,c,d], [a,b,c-2,d], [a,b,c,d-2]. Is that correct?
 Got it. The valid neighbors of the given solution (10, 10, 10, 10) with tabu list = [1,-1,2,-2] are (10,10,12,10), (10,10,10,12), (10,10,8,10), (10,10,10,8). Is there anything else I can help you with?
 The valid neighbors of the given solution (20, 20, 20, 20) with tabu list = [1,-1,3,-3] are (20,20,23,20), (20,20,20,23), (20,20,17,20), (20,20,20,17).
[[20,52,70,100,2], [20,48,70,100,-2], [20,50,72,100,3], [20,50,68,100,-3], [20,50,70,102,4], [20,50,70,98,-4], [18,50,70,100,-1], [22,50,70,100,1]]
[[ 20  52  70 100   2]
 [ 20  48  70 100  -2]
 [ 20  50  72 100   3]
 [ 20  5

KeyboardInterrupt: 